allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true

patchedDependencies:
  vitepress@2.0.0-alpha.17: patches/vitepress@2.0.0-alpha.17.patch

peerDependencyRules:
  allowedVersions:
    "markdown-it-math@5.2.1>temml": "0.13.2"